# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-engine-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"
        # Ubuntu 22.04.2 LTS - Jammy Jellyfish
        # d.vm.box = "ubuntu/jammy64"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-engine-shell-1"
            vb.memory = "4048"
            vb.gui = true
        end

        # docker registry port
        config.vm.network :forwarded_port, guest: 5000, host: 5000
        # application port
        config.vm.network :forwarded_port, guest: 8080, host: 8080
        # TODO: forward docker engine ports: 2375, 32769 .. ?

        d.vm.provision "shell", path: "root-login-enable.sh"
#         d.vm.provision "shell", path: "docker-repository.sh"
        d.vm.provision "shell", path: "docker-engine.sh"
    end
end