# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "alpine-1" do |d|
        d.vm.box = "generic/alpine318"

        config.vm.synced_folder File.expand_path('~/.vagrant.d'), "/secrets"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "alpine-1"
            vb.memory = "4048"
            # vb.memory = "8192"
            # vb.cpus = 8
            # vb.gui = true
            # vb.customize ["modifyvm", :id, "--bioslogodisplaytime", "20000"]
            # vb.customize ['setextradata', :id, 'GUI/ScaleFactor', '3.00']
            # vb.customize ['setextradata', :id, 'GUI/SuppressMessages', 'confirmGoingFullscreen,remindAboutMouseIntegration,remindAboutAutoCapture']
        end

        d.vm.network :private_network, ip: "192.168.56.2"

        # d.vm.provision "shell", path: "root-login-enable.sh"
        # d.vm.provision "shell", path: "provision.sh"
    end

    config.vm.post_up_message = "The application is available at http://abc.example.lh:8765"
end