# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "alpine-1" do |d|
        d.vm.box = "generic/alpine318"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "alpine-1"
            vb.memory = "4048"
            vb.gui = true
        end

        d.vm.network :private_network, ip: "192.168.56.2"

        # d.vm.provision "shell", path: "root-login-enable.sh"
        # d.vm.provision "shell", path: "provision.sh"
    end
end