VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.box = 'oraclelinux/7'
  config.vm.box_url = 'https://oracle.github.io/vagrant-projects/boxes/oraclelinux/7.json'

  config.vm.network :private_network, ip: "192.168.56.2"
  config.vm.provision 'shell', path: 'provision.sh'

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
    v.gui = true
  end
end