# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-artemis-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-artemis-1"
            vb.memory = "4048"
        end

        d.vm.provision "shell", path: "root-login-enable.sh"

        d.vm.provision :docker do |dc|
            dc.run "apache/activemq-artemis", args: "-p 61616:61616 -p 8161:8161"
        end
    end

    config.vm.network :forwarded_port, guest: 8161, host: 8161
    config.vm.network :forwarded_port, guest: 61616, host: 61616
end