# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :name => 'm1', :ip => '192.168.56.2'}

  # { :name => 's1', :ip => '192.168.56.3'}
  # { :name => 's2', :ip => '192.168.56.4'}
]

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder '.', '/vagrant'
    # config.vm.provision "docker"

    nodes.each do |node|
        config.vm.define node[:name] do |d|
            d.vm.hostname = "#{node[:name]}.szolotukhin.in.ua"
            d.vm.network :private_network, ip: node[:ip]
            d.vm.provider :virtualbox do |v|
                v.name = "docker swarm #{node[:name]}"
                v.gui = true
                v.memory = "1024"
                v.customize ["modifyvm", :id, "--vram", "128"]
            end

            d.vm.provision "ansible_local" do |ansible|
                # ansible.compatibility_mode = "2.0"
                ansible.playbook = "ansible/playbook.yml"
                # ansible.inventory_path = "ansible/inventory"
                # ansible.limit = "all"
            end
        end
    end
end

