services:
  db:
    container_name: postgres
    image: postgres
    profiles: ["postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  oracle-db:
    container_name: oracle
    image: container-registry.oracle.com/database/express:21.3.0-xe
    pull_policy: never
    profiles: ["oracle"]
    environment:
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup

volumes:
  db:
  oracle-data:
  oracle-backup: