# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-engine-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        # d.vm.box = "ubuntu/focal64"
        # Ubuntu 22.04.2 LTS - Jammy Jellyfish
        d.vm.box = "ubuntu/jammy64"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-engine-1"
            vb.memory = "4048"
            vb.gui = true
        end

        d.vm.network :private_network, ip: "192.168.56.2"

        d.vm.provision "shell", path: "root-login-enable.sh"

        # Install Docker Engine
        d.vm.provision :docker do |dc|
          dc.post_install_provision "shell", path: "docker-remote-access.sh"
        end

        # Install Docker Compose
        # First, install required plugin https://github.com/leighmcculloch/vagrant-docker-compose:
        # vagrant plugin install vagrant-docker-compose
        # d.vm.provision :docker_compose, rebuild: true, run: "always", yml: "/vagrant/docker-compose.yml"
    end
end