# -*- mode: ruby -*-
# vi: set ft=ruby :

# unless Vagrant.has_plugin?("vagrant-persistent-storage")
#   abort 'The Vagrant vagrant-persistent-storage plugin must be install prior to building this VM (vagrant plugin install vagrant-persistent-storage)'
# end

# disk = './.vagrant/persistence-disk-01.vdi'

Vagrant.configure("2") do |config|
  # Ubuntu 20.04.3 LTS - Focal Fossa
  # config.vm.box = "ubuntu/focal64"
  # Ubuntu 22.04.2 LTS - Jammy Jellyfish
  config.vm.box = "ubuntu/jammy64"

  # second disk
  # config.persistent_storage.enabled = true
  # config.persistent_storage.location = disk
  # config.persistent_storage.size = 5000
  # config.persistent_storage.mountname = 'mysql'
  # config.persistent_storage.filesystem = 'ext4'
  # config.persistent_storage.mountpoint = '/var/lib/mysql'
  # config.persistent_storage.diskdevice = '/dev/sdc'

  config.vm.provider :virtualbox do |vb|
    vb.name = "multiple-disks-1"
    vb.memory = "2048"
    vb.cpus = 2
    vb.gui = true
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision/apt-update.sh"
  config.vm.provision "shell", path: "provision/root-login-enable.sh"
  # config.vm.provision "shell", path: "provision/partitions.sh"
  # config.vm.provision "shell", path: "provision/install-postgresql.sh"
  config.vm.provision "shell", path: "provision/install-tools.sh"
  # config.vm.provision :szshell, args: "Hello Serhij Zolotukhin"

  # config.trigger.after :halt do |trigger|
  #   trigger.info = "Detache storage"
  #   trigger.ruby do |env, machine|
  #     machine.provider.driver.execute('storageattach', machine.id, '--storagectl', 'SCSI', '--port', '2', '--device', '0', '--type', 'hdd', '--medium', 'none', retryable: true)
  #   end
  # end

  config.trigger.before :environment_load, type: :hook do |t|
    t.info = 'NEVER CALLED'
    t.ruby do |env, machine|
      raise 'NEVER RAISED'
    end
  end

  # config.hostmanager.enabled = true
  # config.hostmanager.manage_host = true
  # config.hostmanager.manage_guest = true
end