# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "docker-jaeger-1" do |d|
        # https://documentation.ubuntu.com/project/release-team/list-of-releases/
        # Ubuntu 20.04.3 LTS - Focal Fossa
        # d.vm.box = "ubuntu/focal64"
        # Ubuntu 22.04.2 LTS - Jammy Jellyfish
        d.vm.box = "ubuntu/jammy64"
        # Ubuntu 24.04.3 LTS - Noble Numbat
        # Ubuntu 25.10 - Questing Quokka

        d.vm.provider "virtualbox" do |vb|
            vb.name = "docker-jaeger-1"
            vb.memory = "4048"
            vb.gui = true
        end

        d.vm.network :private_network, ip: "192.168.56.2"

        d.vm.provision "shell", path: "provision/root-login-enable.sh"

        # Install Docker Engine / Docker Compose plugin
        d.vm.provision :docker do |dc|
          dc.post_install_provision "shell", path: "provision/docker-remote-access.sh"
        end
    end
end