# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # https://wiki.ubuntu.com/Releases

  # Ubuntu 23.10 - Mantic Minotaur
  # config.vm.box = "ubuntu/mantic64"

  # Ubuntu 23.04 - Lunar Lobster
  # config.vm.box = "ubuntu/lunar64"

  # Ubuntu 22.04 LTS - Jammy Jellyfish
  # config.vm.box = "ubuntu/jammy64"
  config.vm.box = "bento/ubuntu-22.04"

  # Ubuntu 20.04 LTS - Focal Fossa
  # config.vm.box = "ubuntu/focal64"
  # config.vm.box = "bento/ubuntu-20.04"

  # config.vm.box_check_update = false
  config.vm.network :private_network, ip: "192.168.56.2"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vagrant-mssql"
    vb.memory = "4096"
    vb.cpus = 4
    vb.gui = true
  end

  config.vm.provision 'shell', path: 'bootstrap.sh'

end
