# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: "192.168.56.2"

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "vagrant-mssql"
    vb.memory = "4096"
    vb.cpus = 4
    override.vm.box = "bento/ubuntu-16.04"
  end

  config.vm.provision 'shell', path: 'bootstrap.sh'

end
