# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "kubernetes-master-1" do |d|
    # https://documentation.ubuntu.com/project/release-team/list-of-releases/
    # Ubuntu 24.04.3 LTS - Noble Numbat
    # Ubuntu 25.04 - Plucky Puffin
    d.vm.box = "bento/ubuntu-25.04"
    d.vm.box_version = "202510.26.0"


    # Ubuntu 25.10 - Questing Quokka

    d.vm.provider "virtualbox" do |vb|
      vb.name = "kubernetes-master-1"
      vb.memory = "4048"
      vb.gui = true
    end

    d.vm.network :private_network, ip: "192.168.56.2"

    d.vm.provision "shell", path: "provision/root-login-enable.sh"

    # Install Docker Engine / Docker Compose plugin
    # d.vm.provision :docker do |dc|
    #   dc.post_install_provision "shell", path: "provision/docker-remote-access.sh"
    # end

    # Run Docker Compose file
    # d.vm.provision "shell", inline: "docker compose --file /vagrant/docker-compose.yml down"
    # d.vm.provision "shell", inline: "docker compose --file /vagrant/docker-compose.yml up --quiet-pull --detach "
    # d.vm.provision "shell", inline: "/vagrant/sh/install.sh"
  end
end