# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "nginx-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"
        # Ubuntu 22.04.2 LTS - Jammy Jellyfish
        # d.vm.box = "ubuntu/jammy64"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "nginx-1"
            vb.memory = "4048"
            vb.gui = true
        end

        d.vm.network :private_network, ip: "192.168.56.2"

        d.vm.provision "shell", path: "root-login-enable.sh"
        d.vm.provision "shell", path: "provision.sh"
    end
end