# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # https://wiki.ubuntu.com/Releases
    # https://ubuntu.com/download/server
    # Ubuntu 22.04.2 LTS - Jammy Jellyfish
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provider :virtualbox do |vb|
        vb.name = "jenkins"
        vb.memory = "2048"
        vb.gui = true
    end

    config.vm.provision "shell", path: "root-login-enable.sh"
    # config.vm.provision "shell", path: "bare-provision.sh"
    config.vm.provision "shell", path: "provision.sh"
end