# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # https://wiki.ubuntu.com/Releases
    # https://ubuntu.com/download/server
    # https://portal.cloud.hashicorp.com/vagrant/discover?query=ubuntu

    # Ubuntu 24.04.2 LTS - Noble Numbat
    # config.vm.box = "bento/ubuntu-24.04"
    # Ubuntu 22.04.2 LTS - Jammy Jellyfish
    config.vm.box = "ubuntu/jammy64"
    # Ubuntu 20.04.3 LTS - Focal Fossa
    # config.vm.box = "ubuntu/focal64"

    # https://www.virtualbox.org/manual/ch06.html
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provider :virtualbox do |vb|
        vb.name = "jenkins"
        vb.memory = "2048"
        vb.gui = true
    end

    config.vm.provision "shell", path: "root-login-enable.sh"
    # config.vm.provision "shell", path: "bare-provision.sh"
    config.vm.provision "shell", path: "provision.sh"
end