# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "ubuntu-lunar-desktop-1" do |d|
        # Ubuntu 20.04.3 LTS - Focal Fossa
        d.vm.box = "ubuntu/focal64"
        # UUbuntu 23.10 (Mantic Minotaur)
        # d.vm.box = "ubuntu/mantic64"

        d.vm.network "public_network"

        d.vm.provider "virtualbox" do |vb|
            vb.name = "ubuntu-lunar-desktop"
            vb.memory = "8096"
            vb.gui = true
        end

        d.vm.network :private_network, ip: "192.168.56.2"
        d.vm.synced_folder "../", "/zoo-keeper"

        d.vm.provision "shell", path: "root-login-enable.sh"
    end
end