# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Ubuntu 20.04.3 LTS - Focal Fossa
    # config.vm.box = "ubuntu/focal64"
    # Ubuntu 22.04.2 LTS - Jammy Jellyfish
    config.vm.box = "ubuntu/jammy64"

    config.vm.network :private_network, ip: "192.168.56.2"

    config.vm.provider :virtualbox do |vb|
        vb.name = "postgresql-1"
        vb.memory = "2048"
        vb.cpus = 2
#         vb.memory = "8192"
#         vb.cpus = 8
        vb.gui = true
    end

    config.vm.network :forwarded_port, guest: 5432, host: 5432
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "shell", path: "root-login-enable.sh"
    config.vm.provision "shell", path: "install-postgresql.sh"
end