# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # https://wiki.ubuntu.com/Releases

    # Ubuntu 23.10 - Mantic Minotaur
    # config.vm.box = "ubuntu/mantic64"

    # Ubuntu 23.04 - Lunar Lobster
    # config.vm.box = "ubuntu/lunar64"

    # Ubuntu 22.04 LTS - Jammy Jellyfish
    # config.vm.box = "ubuntu/jammy64"
    # config.vm.box = "bento/ubuntu-22.04"

    # Ubuntu 20.04 LTS - Focal Fossa
    config.vm.box = "ubuntu/focal64"
    # config.vm.box = "bento/ubuntu-20.04"

    config.vm.provider :virtualbox do |vb|
        vb.name = "postgresql-1"
        vb.memory = "2048"
        vb.cpus = 2
#         vb.memory = "8192"
#         vb.cpus = 8
        vb.gui = true
    end

    config.vm.network :forwarded_port, guest: 5432, host: 5432
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provision "shell", path: "root-login-enable.sh"
    config.vm.provision "shell", path: "install-postgresql.sh"
end